version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/backend_static
      - media:/app/media 

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.25.4-alpine
    depends_on:
      - backend
    ports:
#      Это настройка для локального запуска 80:80
#      - "8000:80"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - media:/app/media
      - static:/app/backend_static
