# Константы для рецептов
NAME_MAX_LENGTH = 150
TAG_NAME_MAX_LENGTH = 50
MEASUREMENT_NAME_MAX_LENGTH = 10
SHORT_URL_CODE_MAX_LENGTH = 6
MIN_AMOUNT = 1

TIME_FAST = 30
TIME_MEDIUM = 60
TIME_MAX = 10000

FAST_COOKING_TIME = (0, TIME_FAST)
MEDIUM_COOKING_TIME = (TIME_FAST, TIME_MEDIUM)
LONG_COOKING_TIME = (TIME_MEDIUM, TIME_MAX)
