# Константы для рецептов
NAME_MAX_LENGTH = 150
TAG_NAME_MAX_LENGTH = 50
MEASUREMENT_NAME_MAX_LENGTH = 10
SHORT_URL_CODE_MAX_LENGTH = 6
MIN_AMOUNT = 1
MIN_COOKING_TIME = 1

TIME_FAST = 30
TIME_MEDIUM = 60
TIME_MAX = 10000
