# Generated by Django 3.2 on 2024-10-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscriptions',
            options={'ordering': ['user', 'author'], 'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
    ]
