# Generated by Django 3.2 on 2024-10-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usershoppinglist',
            name='usershoppinglist_user_recipe_unique',
        ),
        migrations.AddConstraint(
            model_name='usershoppinglist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_shopping_list'),
        ),
    ]
