# Generated by Django 3.2 on 2024-09-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_url_code',
            field=models.CharField(max_length=6, unique=True, verbose_name='Код короткой ссылки'),
        ),
    ]
