# Generated by Django 3.2 on 2024-09-25 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgramuser',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
