# Generated by Django 3.2 on 2024-10-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_usersubscriptions_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='name_measurement_unit_unique',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_name_measurement_unit'),
        ),
    ]
