# Generated by Django 3.2 on 2024-10-21 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20241018_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_url_code',
            field=models.CharField(blank=True, max_length=6, unique=True, verbose_name='Код короткой ссылки'),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_users', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
